# Generated by Django 3.1.5 on 2024-10-02 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0003_auto_20240813_1753'),
        ('health_center', '0010_auto_20240727_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ann_date', models.DateTimeField(default='04-04-2021')),
                ('message', models.CharField(max_length=200)),
                ('upload_announcement', models.FileField(default=' ', null=True, upload_to='health_center/upload_announcement')),
                ('anno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements_made', to='globals.extrainfo')),
            ],
        ),
    ]
