# Generated by Django 3.1.5 on 2024-10-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_center', '0011_announcements'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical_relief',
            name='compounder_reject_flag',
            field=models.BooleanField(default=False),
        ),
    ]
